export type FreshnessLevel = 'REALTIME' | 'DELAYED' | 'STALE';
export type ConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW';
export type CatalystImpact = 'BULLISH' | 'BEARISH' | 'NEUTRAL';
export type DiffSeverity = 'CRITICAL' | 'MODERATE' | 'LOW' | 'UNCHANGED';
export type BaselineType = 'USER_COMMIT' | 'AUTO_SESSION' | 'TODAY_OPEN' | 'PREVIOUS_CLOSE';

export type DataSourceReason =
  | 'LIVE_STREAM'
  | 'MARKET_CLOSED'
  | 'RATE_LIMITED'
  | 'TIMEOUT'
  | 'SOURCE_UNAVAILABLE'
  | 'SYNTHETIC_MODE';

export interface DataSourceStatus {
  isLive: boolean;
  reason: DataSourceReason;
  label: string; // e.g., "Live Market Data (NSE)", "Simulated (Market Closed)"
  description: string;
  asOf: number;
  isMarketHours: boolean;
}

export interface DataSourceConfidence {
  level: ConfidenceLevel;
  isDivergent: boolean; // True if primary and secondary providers disagree (>0.30% delta)
  divergencePercent?: number; // Spread between feeds (e.g. 0.85%)
  primaryProvider: string; // e.g., "NSE Realtime Feed", "Yahoo Finance Live", "Deterministic Sim"
  secondaryProvider?: string; // e.g., "BSE Fallback", "Synthetic Sim"
  asOf: number; // Unix timestamp (ms) when quote was fetched
  dataSourceReason?: DataSourceReason;
  isLiveData?: boolean;
}

export interface CatalystEvent {
  id: string;
  symbol: string;
  timestamp: number;
  headline: string;
  source: string;
  impact: CatalystImpact;
  summary: string;
  category: 'EARNINGS' | 'MACRO' | 'PRODUCT' | 'ANALYST' | 'LEGAL' | 'GENERAL';
}

export interface CorrelationBreakEvent {
  id: string;
  tickerA: string;
  tickerB: string;
  nameA: string;
  nameB: string;
  historicalCorrelation: number; // Pearson r coefficient (e.g., 0.88)
  deltaA: number; // Percent delta ticker A (e.g., +5.2%)
  deltaB: number; // Percent delta ticker B (e.g., +0.1%)
  spreadPercent: number; // Absolute delta spread (e.g., 5.1%)
  severity: 'CRITICAL' | 'MODERATE';
  headline: string;
  summary: string;
  timestamp: number;
}

export interface TickerState {
  symbol: string;
  name: string;
  price: number;
  open: number;
  high: number;
  low: number;
  volume: number;
  avgVolume: number;
  peRatio?: number;
  marketCap: number;
  rsi14: number;
  macd: { value: number; signal: number; histogram: number };
  sparkline: number[];
  activeCatalysts: CatalystEvent[];

  // --- Data Freshness & Source Confidence ---
  freshness: FreshnessLevel; // REALTIME (<30s), DELAYED (30s-15m), STALE (>15m)
  dataAgeMs: number;
  confidence: DataSourceConfidence;
}

export interface UserWatchlist {
  id: string;
  userId: string;
  name: string;
  symbols: string[];
  createdAt: number;
  updatedAt: number;
}

export interface WatchlistSnapshot {
  id: string;
  userId: string;
  watchlistId?: string; // Scoped watchlist ID for multi-watchlist isolation
  name: string; // e.g. "Today's Market Open (09:15 AM)", "Pre-CPI Release", "Session Close"
  timestamp: number;
  isSyntheticColdStart?: boolean; // Set to true if generated from fallback baseline
  baselineType: BaselineType;
  tickers: Record<string, TickerState>;
}

export interface TickerDiff {
  symbol: string;
  name: string;
  basePrice: number;
  targetPrice: number;
  priceDelta: number;
  percentDelta: number;
  volumeRatio: number; // target volume vs base or daily avg
  indicatorShifts: {
    rsiChange: number;
    rsiStatus: 'NORMAL' | 'OVERBOUGHT_ENTERED' | 'OVERSOLD_ENTERED';
    macdCross: 'BULLISH_CROSS' | 'BEARISH_CROSS' | 'NONE';
  };
  newCatalysts: CatalystEvent[];
  priorityScore: number; // 0 to 100 attention score
  severity: DiffSeverity;
  keyTakeaway: string;
  isAiNarrated?: boolean; // True if generated by LLM, false/undefined if templated fallback
  templatedTakeaway?: string; // Original deterministic rule-based takeaway
  correlationBreak?: CorrelationBreakEvent; // Attached if this ticker is in a decoupled pair

  // Data Quality & Precision Context for Frontend Visual Degradation
  targetFreshness: FreshnessLevel;
  dataAgeMs: number;
  confidence: DataSourceConfidence;
  isDegraded: boolean;
  confidenceNote?: string;
  sparkline: number[];
}

export interface WatchlistDiffReport {
  baseSnapshot: {
    id: string;
    name: string;
    timestamp: number;
    baselineType: BaselineType;
    isSyntheticColdStart: boolean;
  };
  targetSnapshot: {
    id: string;
    name: string;
    timestamp: number;
  };
  portfolioDeltaPercent: number;
  topGainer: TickerDiff | null;
  topLoser: TickerDiff | null;
  mostActive: TickerDiff | null;
  diffs: TickerDiff[];
  totalNewCatalysts: number;
  correlationBreaks: CorrelationBreakEvent[]; // Pair correlation breaks
  generatedAt: number;

  // Cold-Start Metadata
  coldStart: {
    isColdStart: boolean;
    message?: string;
    fallbackBaselineUsed: 'TODAY_OPEN' | 'PREVIOUS_CLOSE' | 'NONE';
  };

  // Overall Feed Quality & Live Status
  dataQualitySummary: {
    staleCount: number;
    divergenceCount: number;
    overallConfidence: ConfidenceLevel | 'DEGRADED';
  };
  dataSourceStatus?: DataSourceStatus;
}

export interface Watchlist {
  userId: string;
  symbols: string[];
  lastSeenSnapshotId: string | null;
  updatedAt: number;
}
